github: [metadata]
theme: jekyll-theme-hacker
title: Lansing Homeschool Hackers
description: Online home of the Lansing Homeschool Hackers, Lansing, MI
# google_analytics: [Your Google Analytics tracking ID]
navigation:
 - title: Home
   url: /index.html
 - title: Resources
   url: /resources.html
 - title: Blog
   url: /posts.html
# Disqus Comments
disqus:
  shortname: lansing-homeschool
plugins:
  - jekyll-feed
